# Generated by Django 6.1.1 on 2026-09-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('job_name', models.CharField(max_length=255)),
                ('daily_link', models.URLField(blank=True, default='')),
                ('prejob_link', models.URLField(blank=True, default='')),
                ('postjob_link', models.URLField(blank=True, default='')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
