# Generated by Django 6.1.1 on 2026-09-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('employee_id', models.CharField(blank=True, default='', max_length=50)),
                ('position', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Personnel',
                'ordering': ['full_name'],
            },
        ),
    ]
