# Generated by Django 6.1.1 on 2026-09-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255)),
                ('client', models.CharField(blank=True, default='', max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('equipment_list', models.TextField(blank=True, default='', help_text='Equipment used on this job (free text list).')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
