# Generated by Django 6.1.1 on 2026-09-07 15:00

import django.db.models.deletion
import equipment.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Units', 'Units'), ('PCE', 'PCE'), ('Down Hole Tools', 'Down Hole Tools'), ('Flange', 'Flange'), ('Crossover', 'Crossover'), ('Safety Device', 'Safety Device'), ('Lifting Gears', 'Lifting Gears'), ('Instrument', 'Instrument')], max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'ordering': ['category', 'serial_number'],
            },
        ),
        migrations.CreateModel(
            name='CategoryCertRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Units', 'Units'), ('PCE', 'PCE'), ('Down Hole Tools', 'Down Hole Tools'), ('Flange', 'Flange'), ('Crossover', 'Crossover'), ('Safety Device', 'Safety Device'), ('Lifting Gears', 'Lifting Gears'), ('Instrument', 'Instrument')], max_length=50)),
                ('cert_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.certtype')),
            ],
            options={
                'unique_together': {('category', 'cert_type')},
            },
        ),
        migrations.CreateModel(
            name='EquipmentCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_number', models.CharField(blank=True, default='', max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=equipment.models.cert_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('cert_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.certtype')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certs', to='equipment.equipment')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text="Who uploaded/last replaced this file — an audit trail your Streamlit app didn't have.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('equipment', 'cert_type')},
            },
        ),
    ]
